### ISSUE TITLE
NameError: name 'task_cls' is not defined

### ISSUE THREAD

**Issue by smurf-1119** [MonashAI/QTool#8]
When I run the code "python tools.py --keyword update,raw --mf weights/det-resnet18/mf.txt --mt weights/det-resnet18/mt.txt --old weights/pytorch-resnet18/resnet18-5c106cde.pth --new weights", I encounter the issue as follows:
![image](https://user-images.githubusercontent.com/63043716/170225322-efcd4262-e302-4b2e-b421-0b53c65c67bb.png)
How can I solve it?

**Comment by smurf-1119** [comment]
More details:
(STR) root@node03:~/data/qu/model-quantization# python tools.py --keyword update,raw --mf weights/det-resnet18/mf.txt --mt weights/det-resnet18/mt.txt --old weights/pytorch-resnet18/resnet18-5c106cde.pth --new weights
Failing to import plugin, ModuleNotFoundError("No module named 'plugin'",)
loading third party model failed cannot import name 'model_zoo'
Traceback (most recent call last):
  File "tools.py", line 11, in <module>
    import main as entry
  File "/root/data/qu/model-quantization/main.py", line 4, in <module>
    task_cls.py
NameError: name 'task_cls' is not defined
